#!/bin/bash
# This is a small util to send reports as attachment to an individual recipient

recipient=$1
filepath=$2

function zfind() {
  zfilepath=$1
  find $filepath -mtime -1 -type f
}

function zemail() {
  zrecipient=$1
  zfilepath=$2
  echo "Please find attached the file." | mailx -s "File as was generated by job GGG" -a $zfile $recipient
}

zfile=$(zfind $filepath)

if [ -z $zfile ]; then
  exit 99;
else
  zemail $recipient $zfile
fi

sleep 60

mv $zfile $filepath/Archive
